apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}
  labels:
    {{- include "app.labels" . | indent 4}}
data:
  {{- range $key,$value := .Values.configMapData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}